### PR TITLE
Adds a gaussian process (GP) regression nonlinearity.

### PR DESCRIPTION
**Pull request by nirum**
This adds a GP regression model for nonlinearities.

It uses the [GPy](https://github.com/SheffieldML/GPy) library to fit GP Regression models, which allows us to model both a mean nonlinearity and uncertainty (variance) around the nonlinearity.

### CODE REVIEW

**Comment by nirum** [comment]
@bnaecker is it cool if I merge?

**Comment by nirum** [comment]
screen shot 2016-09-09 at 5 13 14 pm

**Comment by nirum** [comment]
^ example of a nonlinearity fit using Binterp vs. GaussianProcess

**Comment by bnaecker** [comment]
This looks good to me. I think just update the `requirements.txt` to make sure setup still works fine, and I'm good with merging.

**Comment by nirum** [comment]
The GPy is not technically required, it will throw an error if you don't have it. I could add it to requirements.txt and make it a dependency, thoughts?

On Sep 9, 2016, at 6:49 PM, bnaecker <notifications@github.com<mailto:notifications@github.com>> wrote:


This looks good to me. I think just update the requirements.txt to make sure setup still works fine, and I'm good with merging.

-

**Comment by bnaecker** [comment]
Ah, I see. I think it’s fine to keep as-is for now.

**Pull request merged**
